# Extra autostart processes
# exec-once = uwsm-app -- my-service
exec-once = hyprpm reload -n
exec-once = nwg-dock-hyprland -p left -i 56 -nolauncher -a center -ml 4 -d -hl top -hd 0 -s style.css
exec-once = ~/.config/hypr/scripts/external-monitor-workspaces.sh
