source = ~/.config/omarchy/current/theme/hyprlock.conf

general {
    ignore_empty_input = true
}

background {
    monitor =
    color = $color
    path = ~/.config/omarchy/current/background
    blur_passes = 3
}

animations {
    enabled = false
}

input-field {
    monitor =
    size = 650, 100
    position = 0, 0
    halign = center
    valign = center

    inner_color = $inner_color
    outer_color = rgb(ff69b4) rgb(4b0082) 45deg
    outline_thickness = 1

    font_family = MesloLGS Nerd Font
    font_color = $font_color

    placeholder_text = <span> Enter Password 󰈷 </span>
    check_color = $check_color
    fail_text = <i>$FAIL ($ATTEMPTS)</i>

    rounding = 15
    shadow_passes = 0
    fade_on_empty = false
}

auth {
    fingerprint:enabled = true
}
