#      dMMMMMP dMP dMP dMMMMMP dMMMMb dMMMMMMP
#     dMP     dMP dMP dMP     dMP dMP   dMP
#    dMMMP   dMP dMP dMMMP   dMP dMP   dMP
#   dMP      YMvAP" dMP     dMP dMP   dMP
#  dMMMMMP    VP"  dMMMMMP dMP dMP   dMP
#
#      dMP dMP .aMMMb  dMMMMb  dMP dMMMMMP .aMMMb  dMMMMb
#     dMP dMP dMP"dMP dMP.dMP amr   .dMP" dMP"dMP dMP dMP
#    dMMMMMP dMP dMP dMMMMK" dMP  .dMP"  dMP dMP dMP dMP
#   dMP dMP dMP.aMP dMP"AMF dMP .dMP"   dMP.aMP dMP dMP
#  dMP dMP  VMMMP" dMP dMP dMP dMMMMMP  VMMMP" dMP dMP
#



[window]
opacity = 0.88

[colors]
transparent_background_colors = true

[colors.primary]
background = "#ffffff"
foreground = "#1e0e30"

[colors.normal]
black   = "#ede8f8"
red     = "#c02040"
green   = "#1a8c64"
yellow  = "#b86000"
blue    = "#0878a8"
magenta = "#c63c8e"
cyan    = "#108a8a"
white   = "#1e0e30"

[colors.bright]
black   = "#8e8bb0"
red     = "#e04068"
green   = "#22bb88"
yellow  = "#d07800"
blue    = "#1898c8"
magenta = "#e848aa"
cyan    = "#18aab0"
white   = "#1e0e30"

[colors.cursor]
text   = "#ffffff"
cursor = "#ff69b4"

#
#  _______/\\\\\_______/\\\\\\____________/\\\__
#   _____/\\\///\\\____\////\\\___________\/\\\__
#    ___/\\\/__\///\\\_____\/\\\___________\/\\\__
#     __/\\\______\//\\\____\/\\\___________\/\\\__
#      _\/\\\_______\/\\\____\/\\\______/\\\\\\\\\__
#       _\//\\\______/\\\_____\/\\\_____/\\\////\\\__
#        __\///\\\__/\\\_______\/\\\____\/\\\__\/\\\__
#         ____\///\\\\\/______/\\\\\\\\\_\//\\\\\\\/\\_
#          ______\/////_______\/////////___\///////\//__
#  ______/\\\\\\\\\\\________________/\\\_______________________/\\\______________________
#   _____\/////\\\///________________\/\\\______________________\/\\\______________________
#    _________\/\\\___________________\/\\\______________________\/\\\______________________
#     _________\/\\\_________/\\\\\____\/\\\____________/\\\\\____\/\\\____________/\\\\\____
#      _________\/\\\_______/\\\///\\\__\/\\\\\\\\\____/\\\///\\\__\/\\\\\\\\\____/\\\///\\\__
#       _________\/\\\______/\\\__\//\\\_\/\\\////\\\__/\\\__\//\\\_\/\\\////\\\__/\\\__\//\\\_
#        __/\\\___\/\\\_____\//\\\__/\\\__\/\\\__\/\\\_\//\\\__/\\\__\/\\\__\/\\\_\//\\\__/\\\__
#         _\//\\\\\\\\\_______\///\\\\\/___\/\\\\\\\\\___\///\\\\\/___\/\\\\\\\\\___\///\\\\\/___
#          __\/////////__________\/////_____\/////////______\/////_____\/////////______\/////_____
#
