#      dMMMMMP dMP dMP dMMMMMP dMMMMb dMMMMMMP
#     dMP     dMP dMP dMP     dMP dMP   dMP
#    dMMMP   dMP dMP dMMMP   dMP dMP   dMP
#   dMP      YMvAP" dMP     dMP dMP   dMP
#  dMMMMMP    VP"  dMMMMMP dMP dMP   dMP
#
#      dMP dMP .aMMMb  dMMMMb  dMP dMMMMMP .aMMMb  dMMMMb
#     dMP dMP dMP"dMP dMP.dMP amr   .dMP" dMP"dMP dMP dMP
#    dMMMMMP dMP dMP dMMMMK" dMP  .dMP"  dMP dMP dMP dMP
#   dMP dMP dMP.aMP dMP"AMF dMP .dMP"   dMP.aMP dMP dMP
#  dMP dMP  VMMMP" dMP dMP dMP dMMMMMP  VMMMP" dMP dMP
#



# Main background, empty for terminal default, need to be empty if you want transparent background
theme[main_bg]="#ffffff"

# Main text color
theme[main_fg]="#1e0e30"

# Title color for boxes
theme[title]="#c63c8e"

# Highlight color for keyboard shortcuts
theme[hi_fg]="#0878a8"

# Background color of selected item in processes box
theme[selected_bg]="#8e8bb0"

# Foreground color of selected item in processes box
theme[selected_fg]="#ffffff"

# Color of inactive/disabled text
theme[inactive_fg]="#8e8bb0"

# Misc colors for processes box including mini cpu graphs, details memory graph and details status text
theme[proc_misc]="#b86000"

# Box outline and divider line color
theme[cpu_box]="#0878a8"
theme[mem_box]="#1a8c64"
theme[net_box]="#108a8a"
theme[proc_box]="#c63c8e"
theme[div_line]="#8e8bb0"

# Gradient for all meters and graphs
theme[temp_start]="#fab795"
theme[temp_mid]="#e95678"
theme[temp_end]="#ec6a88"


theme[cpu_start]="#59e3e3"
theme[cpu_mid]="#26bbd9"
theme[cpu_end]="#29d398"


theme[free_start]="#26bbd9"
theme[free_mid]="#59e3e3"
theme[free_end]="#6be4e6"


theme[cached_start]="#fab795"
theme[cached_mid]="#f075b5"
theme[cached_end]="#ec6a88"


theme[available_start]="#29d398"
theme[available_mid]="#3fdaa4"
theme[available_end]="#26bbd9"


theme[used_start]="#fab795"
theme[used_mid]="#ec6a88"
theme[used_end]="#ee64ac"


theme[download_start]="#59e3e3"
theme[download_mid]="#26bbd9"
theme[download_end]="#29d398"


theme[upload_start]="#fab795"
theme[upload_mid]="#ec6a88"
theme[upload_end]="#ee64ac"

#
#  _______/\\\\\_______/\\\\\\____________/\\\__
#   _____/\\\///\\\____\////\\\___________\/\\\__
#    ___/\\\/__\///\\\_____\/\\\___________\/\\\__
#     __/\\\______\//\\\____\/\\\___________\/\\\__
#      _\/\\\_______\/\\\____\/\\\______/\\\\\\\\\__
#       _\//\\\______/\\\_____\/\\\_____/\\\////\\\__
#        __\///\\\__/\\\_______\/\\\____\/\\\__\/\\\__
#         ____\///\\\\\/______/\\\\\\\\\_\//\\\\\\\/\\_
#          ______\/////_______\/////////___\///////\//__
#  ______/\\\\\\\\\\\________________/\\\_______________________/\\\______________________
#   _____\/////\\\///________________\/\\\______________________\/\\\______________________
#    _________\/\\\___________________\/\\\______________________\/\\\______________________
#     _________\/\\\_________/\\\\\____\/\\\____________/\\\\\____\/\\\____________/\\\\\____
#      _________\/\\\_______/\\\///\\\__\/\\\\\\\\\____/\\\///\\\__\/\\\\\\\\\____/\\\///\\\__
#       _________\/\\\______/\\\__\//\\\_\/\\\////\\\__/\\\__\//\\\_\/\\\////\\\__/\\\__\//\\\_
#        __/\\\___\/\\\_____\//\\\__/\\\__\/\\\__\/\\\_\//\\\__/\\\__\/\\\__\/\\\_\//\\\__/\\\__
#         _\//\\\\\\\\\_______\///\\\\\/___\/\\\\\\\\\___\///\\\\\/___\/\\\\\\\\\___\///\\\\\/___
#          __\/////////__________\/////_____\/////////______\/////_____\/////////______\/////_____
#
