#      dMMMMMP dMP dMP dMMMMMP dMMMMb dMMMMMMP
#     dMP     dMP dMP dMP     dMP dMP   dMP
#    dMMMP   dMP dMP dMMMP   dMP dMP   dMP
#   dMP      YMvAP" dMP     dMP dMP   dMP
#  dMMMMMP    VP"  dMMMMMP dMP dMP   dMP
#
#      dMP dMP .aMMMb  dMMMMb  dMP dMMMMMP .aMMMb  dMMMMb
#     dMP dMP dMP"dMP dMP.dMP amr   .dMP" dMP"dMP dMP dMP
#    dMMMMMP dMP dMP dMMMMK" dMP  .dMP"  dMP dMP dMP dMP
#   dMP dMP dMP.aMP dMP"AMF dMP .dMP"   dMP.aMP dMP dMP
#  dMP dMP  VMMMP" dMP dMP dMP dMMMMMP  VMMMP" dMP dMP
#



# Background and foreground colors
background = #ffffff
foreground = #1e0e30

background-opacity = 0.88

# Standard colors
palette = 0=#ede8f8
palette = 1=#c02040
palette = 2=#1a8c64
palette = 3=#b86000
palette = 4=#0878a8
palette = 5=#c63c8e
palette = 6=#108a8a
palette = 7=#1e0e30

# Bright colors
palette = 8=#8e8bb0
palette = 9=#e04068
palette = 10=#22bb88
palette = 11=#d07800
palette = 12=#1898c8
palette = 13=#e848aa
palette = 14=#18aab0
palette = 15=#1e0e30

#
#  _______/\\\\\_______/\\\\\\____________/\\\__
#   _____/\\\///\\\____\////\\\___________\/\\\__
#    ___/\\\/__\///\\\_____\/\\\___________\/\\\__
#     __/\\\______\//\\\____\/\\\___________\/\\\__
#      _\/\\\_______\/\\\____\/\\\______/\\\\\\\\\__
#       _\//\\\______/\\\_____\/\\\_____/\\\////\\\__
#        __\///\\\__/\\\_______\/\\\____\/\\\__\/\\\__
#         ____\///\\\\\/______/\\\\\\\\\_\//\\\\\\\/\\_
#          ______\/////_______\/////////___\///////\//__
#  ______/\\\\\\\\\\\________________/\\\_______________________/\\\______________________
#   _____\/////\\\///________________\/\\\______________________\/\\\______________________
#    _________\/\\\___________________\/\\\______________________\/\\\______________________
#     _________\/\\\_________/\\\\\____\/\\\____________/\\\\\____\/\\\____________/\\\\\____
#      _________\/\\\_______/\\\///\\\__\/\\\\\\\\\____/\\\///\\\__\/\\\\\\\\\____/\\\///\\\__
#       _________\/\\\______/\\\__\//\\\_\/\\\////\\\__/\\\__\//\\\_\/\\\////\\\__/\\\__\//\\\_
#        __/\\\___\/\\\_____\//\\\__/\\\__\/\\\__\/\\\_\//\\\__/\\\__\/\\\__\/\\\_\//\\\__/\\\__
#         _\//\\\\\\\\\_______\///\\\\\/___\/\\\\\\\\\___\///\\\\\/___\/\\\\\\\\\___\///\\\\\/___
#          __\/////////__________\/////_____\/////////______\/////_____\/////////______\/////_____
#
