#      dMMMMMP dMP dMP dMMMMMP dMMMMb dMMMMMMP
#     dMP     dMP dMP dMP     dMP dMP   dMP
#    dMMMP   dMP dMP dMMMP   dMP dMP   dMP
#   dMP      YMvAP" dMP     dMP dMP   dMP
#  dMMMMMP    VP"  dMMMMMP dMP dMP   dMP
#
#      dMP dMP .aMMMb  dMMMMb  dMP dMMMMMP .aMMMb  dMMMMb
#     dMP dMP dMP"dMP dMP.dMP amr   .dMP" dMP"dMP dMP dMP
#    dMMMMMP dMP dMP dMMMMK" dMP  .dMP"  dMP dMP dMP dMP
#   dMP dMP dMP.aMP dMP"AMF dMP .dMP"   dMP.aMP dMP dMP
#  dMP dMP  VMMMP" dMP dMP dMP dMMMMMP  VMMMP" dMP dMP
#



background            #ffffff
foreground            #1e0e30

background_opacity 0.88

# black
color0  #ede8f8
color8  #8e8bb0

# red
color1  #c02040
color9  #e04068

# green
color2  #1a8c64
color10 #22bb88

# yellow
color3  #b86000
color11 #d07800

# blue
color4  #0878a8
color12 #1898c8

# magenta
color5  #c63c8e
color13 #e848aa

#cyan
color6  #108a8a
color14 #18aab0

#white
color7  #1e0e30
color15 #1e0e30

#
#  _______/\\\\\_______/\\\\\\____________/\\\__
#   _____/\\\///\\\____\////\\\___________\/\\\__
#    ___/\\\/__\///\\\_____\/\\\___________\/\\\__
#     __/\\\______\//\\\____\/\\\___________\/\\\__
#      _\/\\\_______\/\\\____\/\\\______/\\\\\\\\\__
#       _\//\\\______/\\\_____\/\\\_____/\\\////\\\__
#        __\///\\\__/\\\_______\/\\\____\/\\\__\/\\\__
#         ____\///\\\\\/______/\\\\\\\\\_\//\\\\\\\/\\_
#          ______\/////_______\/////////___\///////\//__
#  ______/\\\\\\\\\\\________________/\\\_______________________/\\\______________________
#   _____\/////\\\///________________\/\\\______________________\/\\\______________________
#    _________\/\\\___________________\/\\\______________________\/\\\______________________
#     _________\/\\\_________/\\\\\____\/\\\____________/\\\\\____\/\\\____________/\\\\\____
#      _________\/\\\_______/\\\///\\\__\/\\\\\\\\\____/\\\///\\\__\/\\\\\\\\\____/\\\///\\\__
#       _________\/\\\______/\\\__\//\\\_\/\\\////\\\__/\\\__\//\\\_\/\\\////\\\__/\\\__\//\\\_
#        __/\\\___\/\\\_____\//\\\__/\\\__\/\\\__\/\\\_\//\\\__/\\\__\/\\\__\/\\\_\//\\\__/\\\__
#         _\//\\\\\\\\\_______\///\\\\\/___\/\\\\\\\\\___\///\\\\\/___\/\\\\\\\\\___\///\\\\\/___
#          __\/////////__________\/////_____\/////////______\/////_____\/////////______\/////_____
#
