## Colors
text-color=#1e0e30
border-color=#ff69b4
background-color=#ffffff

## Style (same as dark)
width=480
height=124
padding=14
border-size=3
border-radius=12
font=JetBrainsMono Nerd Font 10
anchor=top-right
outer-margin=20
default-timeout=5000
max-icon-size=32

[app-name=Spotify]
invisible=1

[mode=do-not-disturb]
invisible=true

[mode=do-not-disturb app-name=notify-send]
invisible=false
