# This file is not a full hyprland configuration.
# It is intended to be included in your main hyprland.conf.

$activeBorderColor = rgb(ad2222) rgb(ad2222) rgb(ad2222) rgb(ad2222) rgb(feccca) rgb(ad2222) rgb(ad2222) rgb(ad2222) rgb(ad2222) rgb(ad2222) 35deg

general {
    col.active_border = $activeBorderColor
    border_size = 3
}

group {
    col.border_active = $activeBorderColor
}

decoration {
    rounding = 16
    rounding_power = 1
  }

animations {
    bezier = easeInOutQuant, 0.76, 0, 0.24, 1
    bezier = linear, 0, 0, 1, 1

    # very smooth, premium feel
    bezier = borderSmooth, 0.22, 1, 0.36, 1

    # slightly snappier but still elegant
    bezier = borderSnappy, 0.18, 0.9, 0.25, 1

    # soft balanced curve
    bezier = borderBalanced, 0.4, 0.0, 0.2, 1

    animation = border, 1, 5.5, borderSmooth
    animation = borderangle, 1, 7, borderBalanced


  }
