-- Generated by scripts/hypr2lua.
-- Source: omarchy-city-783-theme/hyprland.conf

local activeBorderColor = {
  colors = { "rgb(ad2222)", "rgb(ad2222)", "rgb(ad2222)", "rgb(ad2222)", "rgb(feccca)", "rgb(ad2222)", "rgb(ad2222)", "rgb(ad2222)", "rgb(ad2222)", "rgb(ad2222)" },
  angle = 35,
}

hl.config({
  general = {
    col = {
      active_border = activeBorderColor,
    },
    border_size = 3,
  },
  group = {
    col = {
      border_active = activeBorderColor,
    },
  },
  decoration = {
    rounding = 16,
    rounding_power = 1,
  },
})

hl.curve("easeInOutQuant", { type = "bezier", points = { { 0.76, 0 }, { 0.24, 1 } } })
hl.curve("linear", { type = "bezier", points = { { 0, 0 }, { 1, 1 } } })
hl.curve("borderSmooth", { type = "bezier", points = { { 0.22, 1 }, { 0.36, 1 } } })
hl.curve("borderSnappy", { type = "bezier", points = { { 0.18, 0.9 }, { 0.25, 1 } } })
hl.curve("borderBalanced", { type = "bezier", points = { { 0.4, 0.0 }, { 0.2, 1 } } })

hl.animation({
  leaf = "border",
  enabled = true,
  speed = 5.5,
  bezier = "borderSmooth",
})
hl.animation({
  leaf = "borderangle",
  enabled = true,
  speed = 7,
  bezier = "borderBalanced",
})
