[colors]
# Match theme terminal transparency behavior.
alpha = 0.45
alpha-mode = all

foreground = fadad1
background = 1c1e26

cursor = fadad1 1c1e26

regular0 = 1c1e26
regular1 = e95678
regular2 = 29d398
regular3 = fab795
regular4 = 26bbd9
regular5 = ee64ac
regular6 = 59e3e3
regular7 = fadad1

bright0 = 6c6f93
bright1 = ec6a88
bright2 = 3fdaa4
bright3 = fbc3a7
bright4 = 3fc4de
bright5 = f075b5
bright6 = 6be4e6
bright7 = fadad1
